openfisca_france_local/departements/cotes_d_armor/fonds_solidarite_logement/base_ressource.py
tests/departements/cotes_d_armor/base_ressource.yml

Les AL sont à prendre en compte dans le calcul du taux d'effort mais pas dans la base ressources.

Supprime les AL de la base ressources

---

openfisca_france_local/metropoles/toulouse/tisseo/ressort_territorial.py
tests/metropoles/toulouse/tisseo/ressort_territorial.yaml

Avant : Seule la villede Toulouse était considérée dans le ressort territorial de Tisséo pour les aides à la mobilité (un raccourci d'implémentation).
Après : Toutes les communes de la métropole sont dans le ressort.

Étend l'éligibilité aux dispositifs à toutes les communes du ressort territoriel de Tisséo

---

setup.py

* En 5.4 un message d'avertissement apparaît vis à vis de la création des test YAML
La correction à faire sur Core n'est pas triviale. Je voudrais mettre ce paquet dans les mains de plus de personnes, cacher le message est une solution temporaire :sweat_smile:

Évite une montée de version mineure

---

setup.py

Met à jour la version d'OpenFisca France pour corriger les warnings Numpy traités dans la PR [#1580](https://github.com/openfisca/openfisca-france/pull/1580).

Met à jour la version OpenFisca France

---

setup.py

Les aides permis MSA nécessitent la version 73.1 d'openfisca-france afin d'utiliser la variable `regime_securite_sociale`

Augmente la version minimale d'openfisca france pour les aides permis MSA

---

.github/workflows/workflow.yml

Le workflow github actions lève une erreur sur mes deux dernières PR : 
```
Error: Version 3.7.12 with arch x64 not found
```
Il semblerai que l'utilisation de la version majeure `3.7` résolve le problème.
La version installée quand on utilise cette valeur est la version `3.7.15` de Python.

Fix workflow - Python setup error : Python not found

---

openfisca_france_local/parameters/regions/auvergne_rhone_alpes/departements.yaml
openfisca_france_local/regions/auvergne_rhone_alpes/eligibilite_residentielle.py
setup.py
tests/regions/auvergne-rhone-alpes/eligibilite_residentielle.yml

- La formule pour évaluer l'éligibilité de résidence dans la région Auvergne Rhône-Alpes ne prenait pas en compte le département de l'Isère

Fix - ajout du département de l'Isère dans la région AURA

---

setup.py

La version 139.0.0 contient l'ajout de la variable `region` nécessaire pour certains de nos travaux.

Monté de version d'openfisca-france vers 139.0.1

---

setup.py

La version d'Openfisca France utilisée sur ce repository était la 139 alors que la version actuelle d'Openfisca France est la 142.0.1.
Cette PR met à jour la version d'Openfisca France utilisée par ce repository en 142.0.1.

Mise à jour OpenFisca-France vers version 142.0.1

---

setup.py

Cette PR met à jour la borne supérieure du numéro de version d'Openfisca France utilisée par ce repository à 143.

Refacto la borne supérieure du numéro de version openfisca-france

---

setup.py

Lors de la dernière release ([v4.2.5](https://github.com/openfisca/openfisca-france-local/pull/141)) nous avons mis à jour la dépendance `openfisca-france` et augmenté la version minimale requise sans faire assez de tests.
Cette PR a pour but de corriger ce problème.
- La version [126.0.0](https://github.com/openfisca/openfisca-france/releases/tag/126.0.0) d'`openfisca-france` introduit le changement du nom de la variable `cmu_forfait_logement_al` en `css_cmu_forfait_logement_al` que nous utilisons dans la formule de la variable `rennes_metropole_transport`.

Fix version minimal dépendance openfisca-france

---

openfisca_france_local/aides_jeunes_reform.py
setup.py
tests/reforms/aides_jeunes/test_aides_jeunes_reform.yaml

---
- Corrige l'erreur de calcul du quotient familiale introduit par la [PR 137](https://github.com/openfisca/openfisca-france-local/pull/137)
- Corrige l'erreur sur le numéro de version minimal des dépendances d'openfisca introduit par inatention lors d'un rebase dans la [PR 130](https://github.com/openfisca/openfisca-france-local/pull/130)

Corrige le calcule du quotient familial sur la réforme dynamique et Corrige les version minimales des dépendances

---

openfisca_france_local/aides_jeunes_reform.py
setup.py
test_data/benefits/test_condition_quotient_familial.yaml
test_data/benefits/test_condition_quotient_familial_year.yaml
tests/reforms/aides_jeunes/test_aides_jeunes_reform.yaml

Le calcule d'éligibilité au quotient familial ne s'adapte pas à la `period` décrite dans le fichier d'aide YAML.
Une aide ayant comme critère d'éligibilité un **quotient familial annuel supérieur à** `9600` sera évalué par comparaison à `9600 \ 12`
Supprime des conditions inutiles dans le fichier de test `test_condition_quotient_familial.yaml`

Réforme - dynamique : Ajoute la gestion de la périodicité à la condition `quotient_familial`

---

setup.py

- Permet à OpenFisca-france-local de fonctionner avec la version 146 d'OpenFisca-france.

Met à jour OpenFisca-france en version 146

---

openfisca_france_local/departements/eure_et_loir/adefip.py
openfisca_france_local/metropoles/rennes/mon_aide.py
setup.py

Modifications apportées afin d'utiliser la version 38.0.2 d'openfisca-core pour être en phase avec openfisca-france.

Utilisation de openfisca-core 38.0.2 

---

CHANGELOG.md
openfisca_france_local/aides_jeunes_reform.py
setup.py

Cette proposition ajoute la possibilité de spécifier le chemin des aides à charger via la `reform_dynamic` par une variable d'environnement `DYNAMIC_BENEFIT_FOLDER`.

Reform_dynamic : Permet de charger le chemin des aides via une variable d'environement

---

CHANGELOG.md
setup.py

Découvert car les changelogs proposés par Dependabot pointait sur Openfisca-France et non Openfisca-France-Local : exemple : https://github.com/betagouv/aides-jeunes/pull/3985

Fix l'url d'openfisca-france-local

---

CHANGELOG.md
openfisca_france_local/aides_jeunes_reform.py
setup.py

_Pour les changements détaillés et les discussions associées, référencez la pull request [#187](https://github.com/openfisca/openfisca-france-local/pull/187)_
- Corrige le crash de la réforme dynamique lors des simulation en mode Tracing

Corrige le traitement des `TracingParameterNodeAtInstant`

---

CHANGELOG.md
setup.py

Complète la mise jour de la contrainte de version max de la dépendance Openfisca France https://github.com/openfisca/openfisca-france-local/pull/207

Met à jour la contrainte max de version OpenFisca France

---

CHANGELOG.md
openfisca_france_local/communes/montpellier/eligibilite.py
openfisca_france_local/communes/montpellier/montpellier_mutuelle_communale.py
setup.py
tests/communes/montpellier/montpellier_mutuelle_communale.yml

Reprise de [cette logique](https://github.com/betagouv/aides-jeunes/blob/bc76ad32e1f698a749be7caf67bb3ecc55bf2cc9/data/benefits/additional-attributes/index.ts#L17-L31) présente dans le simulateur Aides Jeunes pour l'éligibilité à la CSS (ex CMU) :
```js
css_participation_forfaitaire: {
extra: [
{
id: "cmu_c",
entity: "familles",
type: "bool",
openfiscaPeriod: "thisMonth",
},
],
compute: function (result, period) {
return result.cmu_c?.[period]
? true
: result.css_participation_forfaitaire?.[period] || 0
},
},
```

Modélisation de la mutuelle communale de la ville de Montpellier
